// OryCMS Admin — generated by `orycms init`
// Replace this with your admin UI component or use the built-in OryCMS admin.
export default function AdminPage() {
  return (
    <main>
      <h1>OryCMS Admin</h1>
      <p>Configure your admin panel in orycms.config.ts.</p>
    </main>
  );
}
