// OryCMS Admin — generated by `orycms init`
export default function CollectionsPage() {
  return (
    <main>
      <h1>Collections</h1>
      <p>Define your content collections in orycms.config.ts.</p>
    </main>
  );
}
